Updated maintainers, Bumped version.
yuce/pot pull request #28
Opened 2020-09-15 17:05 UTC by yuce

2020-09-16 00:49 UTC, nalundgaard requested changes
Couple of concerns from me called out in the line items.

2020-09-16 00:49 UTC, nalundgaard commented on src/pot.app.src
> +  {maintainers, [
I think we should remove this, the field is deprecated in Hex and results in a publish error on the latest versions of rebar3: https://github.com/tsloughter/rebar3_hex/issues/125

2020-09-16 00:49 UTC, nalundgaard commented on README.md
> +## Useful Links
Does this render? This looks like a markdown links list, I don’t think they are displayed in the rendered output.

2020-09-16 08:07 UTC, yuce commented
Heck, it seems my rebar3 and hex was quite a bit behind. Added you as an owner of the package, hopefully it will work this time.

2020-09-17 23:43 UTC, merged

2020-09-17 23:44 UTC, nalundgaard commented
Cool! All set, I published 1.0.0 just now.

2020-09-18 07:08 UTC, yuce commented
That's great! 🎉🎉🎉